### ISSUE TITLE
Failed to establish a new connection while Edimax SP-2101W is plugged in

### ISSUE THREAD

**Issue by HalinGG** [tback/spx#1]
I'm on a Mac OS X 10.9.5 and using Edimax smartplug switch with power meter (SP-2101W). I tried resetting the device, unplugging and plugging back in.

This is the error I'm getting:

```
p.set_state(True)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/spx/smartplug.py", line 95, in set_state
    state='ON' if self._convert_to_boolean(state) else 'OFF'
  File "/usr/local/lib/python2.7/site-packages/spx/smartplug.py", line 77, in _send_command
    response = requests.post(self.url, data=command)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/sessions.py", line 579, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.8.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.95.79', port=10000): Max retries exceeded with url: /smartplug.cgi (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1038a0450>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```

Thank you for your time!

**Comment by tback** [comment]
The IP Address 169.254.95.79 looks self assigned to me. Are you sure that this is the IP Address of the Smartplug? Did you provide the correct password? The default is username `admin` password `1234`
What is the output of `curl -v 'http://admin:1234@169.254.95.79:10000/smartplug.cgi`?
